version: 2.1

jobs:
  build:
    docker:
      - image: cimg/elixir:1.13.3-node
    working_directory: ~/project/kv
    resource_class: medium
    steps:
      - checkout:
          path: ~/project
      - run: mix do local.hex --force, local.rebar --force
      - run: mix deps.get
